### ISSUE TITLE
About the results on the Leaderboard

### ISSUE THREAD

**Issue by szq0214** [kuangliu/torchcv#11]
Hi @kuangliu,

After reading your README.md file and your code (https://github.com/kuangliu/torchcv/blob/master/examples/ssd/train.py#L38) carefully, I think you made a very serious mistake. The VOC Comp3 Challenge only allows models trained on VOC12 datasets **without VOC07 dataset or any pre-trained models from ImageNet**. Please check this rule carefully. If you used any of them in your training process, please make your results private and re-submit them to VOC Comp4 Challenge: http://host.robots.ox.ac.uk:8080/leaderboard/displaylb.php?challengeid=11&compid=4. Your results may mislead others.

**Comment by kuangliu** [comment]
Thanks man, I didn't notice that.
I published another result that is only trained on VOC12. I'll mark the older one to private.

**Comment by szq0214** [comment]
@kuangliu, do you still use the pre-trained models to obtain the results?
