### ISSUE TITLE
"RuntimeError: seq can't be empty"  in demo.py

### ISSUE THREAD

**Issue by nico1as** [kuangliu/torchcv#15]
Hi, 

Thanks very much for sharing your code. 
I make the taining on my own data (only 2 classes far now) but i have a "RuntimeError: seq can't be empty" when i run the demo.py code.
You'll find below some debug info while running demo.py.

Is it because the model don't find any box with a confidence level up to 0.6? 

Many thanks, 

Nicolas 

```
Loading model..
Loading image..
Predicting..
Decoding..
models/ssd/box_coder.py.decode.num_classes 2
models/ssd/box/coder.py.decode.cls_preds
 9.8710e-01  1.2897e-02
 9.9807e-01  1.9291e-03
 9.9837e-01  1.6258e-03
           ⋮
 9.6491e-01  3.5095e-02
 9.7922e-01  2.0780e-02
 9.7574e-01  2.4260e-02
[torch.FloatTensor of size 24564x2]

models/ssd/box_coder.py.decode.score
 1.2897e-02
 1.9291e-03
 1.6258e-03
     ⋮
 3.5095e-02
 2.0780e-02
 2.4260e-02
[torch.FloatTensor of size 24564]

models/ssd/box_coder.py.decode.score_thresh 0.6
models/ssd/box_coder.py.decode.mask
 0
 0
 0
⋮
 0
 0
 0
[torch.ByteTensor of size 24564]

models/ssd/box_coder.py.decode.boxes []
Traceback (most recent call last):
  File "examples/ssd/demo.py", line 59, in <module>
    loc_preds.data.squeeze(), F.softmax(cls_preds.squeeze(), dim=1).data)
  File "/home/ubuntu/torchcv/torchcv/models/ssd/box_coder.py", line 132, in decode
    boxes = torch.cat(boxes, 0)
RuntimeError: seq can't be empty

```

**Comment by ahkarami** [comment]
Dear @nico1as,
I think you can change (decrease) the value of parameters `score_thresh` & `nms_thresh` in the `box_coder.py` (for example 0.3).
I have also a question. You have mentioned that your data set has 2 classes. So in the training code, set the `num_classes` to **3** or **2**? Because I think, as we have a **Background Class**, so we must set it to 3 instead of 2. Am I correct?

**Comment by nico1as** [comment]
It works, thanks! I've missed the background Class. And I had to adapt the score_thresh to my data.
Best
