### ISSUE TITLE
Bug: class target can't be negative

### ISSUE THREAD

**Issue by lemairecarl** [kuangliu/torchcv#4]
I think there is a problem in the ssd loss at this line:

https://github.com/kuangliu/torchcv/blob/b04e3f11b96e024d932562af342659d7904533f1/torchcv/loss/ssd_loss.py#L63

By looking at the different parts of the code, it seems like `cls_targets` will always be positive. 
I think operator `<` should be replaced by `<=` or simply `==`.

**Comment by kuangliu** [comment]
Actually `class_targets` could be negative.
For example, in [retinanet/box_coder.py](https://github.com/kuangliu/torchcv/blob/master/torchcv/models/retinanet/box_coder.py#L95), I mark `class_targets` of ignored boxes to -1. And the `cls_loss` of ignored boxes should be set to 0.

This line is useless for SSD models. I put it here in case of I wanna train RetinaNet with SSDLoss.

**Comment by lemairecarl** [comment]
Thanks for your answer.
I see. Adding a comment would be nice.
